### PR TITLE
Reorganized package structure for pyi, typed inclusion

### PR DESCRIPTION
**Pull request by flexatone**

### CODE REVIEW

**Comment by flexatone** [comment]
@brandtbucher : This was building correctly locally, but the CI is failing to find the compiled extension module, which I intended with setup.py to go in the `arraykit` package directory. Any ideas?

**Comment by brandtbucher** [comment]
I'll take a peek when I get the chance!

**Comment by brandtbucher** [comment]
Okay, I think I see the issue. The problem is that we run the tests from the root of the repo. Trying to import `arraykit._arraykit` fails, because we've got an `arraykit` package right under us without a built `_arraykit` module inside of it (the actual installed package, on the CI runner, is in `site-packages`).

I believe the fix is just to run the tests from inside of the `test` directory. I make that change tomorrow.

**Comment by flexatone** [comment]
@brandtbucher : Tried changing ci.yml to use this: 
```
          CIBW_TEST_COMMAND: pytest {project}/test
```
But that did not seem to help.

**Comment by brandtbucher** [comment]
Yeah, the issue is deeper (I think because there is a stdlib package already named `test`, and maybe one or two compounding issues. Still working out a fix.

**Review by brandtbucher — APPROVED** [review]
Got it!

**Comment by flexatone** [comment]
Thanks, @brandtbucher , for figuring this out!

**Pull request merged**
